package io

const (
	FldIdx計上年月 int = iota
	FldIdxコストプール
	FldIdx按分ルール1
	FldIdx按分ルール2
	FldIdxNo
	FldIdx取引日
	FldIdx管理番号
	FldIdx借方勘定科目
	FldIdx借方決算書表示名
	FldIdx借方勘定科目ショートカット1
	FldIdx借方勘定科目ショートカット2
	FldIdx借方金額
	FldIdx借方税区分
	FldIdx借方税金額
	FldIdx借方内税外税
	FldIdx借方税率
	FldIdx借方軽減税率有無
	FldIdx借方取引先コード
	FldIdx借方取引先名
	FldIdx借方取引先ショートカット1
	FldIdx借方取引先ショートカット2
	FldIdx借方品目
	FldIdx借方品目ショートカット1
	FldIdx借方品目ショートカット2
	FldIdx借方補助科目名
	FldIdx借方補助科目ショートカット1
	FldIdx借方補助科目ショートカット2
	FldIdx借方部門
	FldIdx借方部門ショートカット1
	FldIdx借方部門ショートカット2
	FldIdx借方メモ
	FldIdx借方メモショートカット1
	FldIdx借方メモショートカット2
	FldIdx借方セグメント1
	FldIdx借方セグメント1ショートカット1
	FldIdx借方セグメント1ショートカット2
	FldIdx借方セグメント2
	FldIdx借方セグメント2ショートカット1
	FldIdx借方セグメント2ショートカット2
	FldIdx借方セグメント3
	FldIdx借方セグメント3ショートカット1
	FldIdx借方セグメント3ショートカット2
	FldIdx借方備考
	FldIdx貸方勘定科目
	FldIdx貸方決算書表示名
	FldIdx貸方勘定科目ショートカット1
	FldIdx貸方勘定科目ショートカット2
	FldIdx貸方金額
	FldIdx貸方税区分
	FldIdx貸方税金額
	FldIdx貸方内税外税
	FldIdx貸方税率
	FldIdx貸方軽減税率有無
	FldIdx貸方取引先コード
	FldIdx貸方取引先名
	FldIdx貸方取引先ショートカット1
	FldIdx貸方取引先ショートカット2
	FldIdx貸方品目
	FldIdx貸方品目ショートカット1
	FldIdx貸方品目ショートカット2
	FldIdx貸方補助科目名
	FldIdx貸方補助科目ショートカット1
	FldIdx貸方補助科目ショートカット2
	FldIdx貸方部門
	FldIdx貸方部門ショートカット1
	FldIdx貸方部門ショートカット2
	FldIdx貸方メモ
	FldIdx貸方メモショートカット1
	FldIdx貸方メモショートカット2
	FldIdx貸方セグメント1
	FldIdx貸方セグメント1ショートカット1
	FldIdx貸方セグメント1ショートカット2
	FldIdx貸方セグメント2
	FldIdx貸方セグメント2ショートカット1
	FldIdx貸方セグメント2ショートカット2
	FldIdx貸方セグメント3
	FldIdx貸方セグメント3ショートカット1
	FldIdx貸方セグメント3ショートカット2
	FldIdx貸方備考
	FldIdx決算整理仕訳
	FldIdx発行元
	FldIdx作成日時
	FldIdx更新日時
	FldIdx承認状況仕訳承認
	FldIdx申請者仕訳承認
	FldIdx申請日時仕訳承認
	FldIdx承認者仕訳承認
	FldIdx承認日時仕訳承認
	FldIdx作成者
	FldIdx消費税経理処理方法
	FldIdx取引ID
	FldIdx口座振替ID
	FldIdx振替伝票ID
	FldIdx仕訳ID
	FldIdx仕訳番号
	FldIdx期末日取引フラグ
	FldIdx取引支払日
	FldIdx仕訳行番号
	FldIdx仕訳行数
	FldIdxレコード番号
	FldIdx取引内容
	FldIdx登録した方法
	FldIdx経費精算申請番号
	FldIdx支払依頼申請番号
)
